sudo: required

services:
  - docker

script:
  - export TRAVIS_DEBIAN_DISTRIBUTION=xenial; tools/docker-ubuntu.sh
  - export TRAVIS_DEBIAN_DISTRIBUTION=sid;    tools/docker-debian.sh

branches:
  except:
    - /^debian\/\d/
