sudo: required

services:
  - docker

script:
  - export TRAVIS_DEBIAN_DISTRIBUTION=sid; wget -O- http://travis.debian.net/script.sh | sh -
  - export TRAVIS_DEBIAN_DISTRIBUTION=xenial; tools/docker-ubuntu.sh

branches:
  except:
    - /^debian\/\d/
